# Generated by Django 4.2.1 on 2023-06-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('u', 'unisex')], max_length=16)),
                ('category', models.CharField(choices=[('shoes', 'shoes'), ('legwear', 'legwear'), ('pants', 'pants'), ('shorts', 'shorts'), ('skirt', 'skirt'), ('t-shirt', 't-shirt'), ('shirt', 'shirt'), ('dress', 'dress'), ('hoodie', 'hoodie'), ('jacket', 'jacket'), ('headwear', 'headwear'), ('gloves', 'gloves')], max_length=16)),
                ('description', models.CharField(max_length=512)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
