# Generated by Django 4.2.1 on 2023-06-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_price',
            field=models.FloatField(default=0),
        ),
    ]
