# Generated by Django 4.2.1 on 2023-06-23 16:15

from django.db import migrations, models
import items.models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=items.models.path_and_rename),
        ),
    ]
