# Generated by Django 4.2.1 on 2023-06-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
