# Generated by Django 4.2.1 on 2023-06-02 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('payment', 'awaiting payment'), ('completed', 'completed'), ('delivery', 'in delivery'), ('shipped', 'shipped')], default=('pending', 'pending'), max_length=16)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=56)),
                ('city', models.CharField(max_length=128)),
                ('postal', models.IntegerField()),
                ('street', models.CharField(max_length=128)),
                ('number', models.CharField(max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
