# Generated by Django 4.2.1 on 2023-06-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'cart'), ('pending', 'pending'), ('payment', 'awaiting payment'), ('completed', 'completed'), ('delivery', 'in delivery'), ('shipped', 'shipped')], default=('cart', 'cart'), max_length=16),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
