# Generated by Django 4.2.1 on 2023-06-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_order_status_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='price_piece',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
