# Generated by Django 4.2.1 on 2023-06-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_order_email_alter_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=128),
        ),
    ]
