# Generated by Django 4.2.1 on 2023-06-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_userpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='UserPayment',
        ),
    ]
